//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3649
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.3649 版自动生成。
// 
#pragma warning disable 1591

namespace Eyousoft_yhq.Web.com._8222666.fxs {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PassengerSegment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FlightSegment))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginForOneOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginByCardNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginExOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoginResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogOffXOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangePwdOperationCompleted;
        
        private System.Threading.SendOrPostCallback XmlSubmitOperationCompleted;
        
        private System.Threading.SendOrPostCallback XmlSubmitDSOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateNewOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerPolicyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Eyousoft_yhq.Web.Properties.Settings.Default.Eyousoft_yhq_Web_com_8222666_fxs_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TestCompletedEventHandler TestCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LoginForOneCompletedEventHandler LoginForOneCompleted;
        
        /// <remarks/>
        public event LoginByCardNoCompletedEventHandler LoginByCardNoCompleted;
        
        /// <remarks/>
        public event LoginExCompletedEventHandler LoginExCompleted;
        
        /// <remarks/>
        public event GetLoginResultCompletedEventHandler GetLoginResultCompleted;
        
        /// <remarks/>
        public event LogOffXCompletedEventHandler LogOffXCompleted;
        
        /// <remarks/>
        public event ChangePwdCompletedEventHandler ChangePwdCompleted;
        
        /// <remarks/>
        public event XmlSubmitCompletedEventHandler XmlSubmitCompleted;
        
        /// <remarks/>
        public event XmlSubmitDSCompletedEventHandler XmlSubmitDSCompleted;
        
        /// <remarks/>
        public event CreateNewOrderCompletedEventHandler CreateNewOrderCompleted;
        
        /// <remarks/>
        public event GetCustomerPolicyCompletedEventHandler GetCustomerPolicyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Test() {
            object[] results = this.Invoke("Test", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestAsync() {
            this.TestAsync(null);
        }
        
        /// <remarks/>
        public void TestAsync(object userState) {
            if ((this.TestOperationCompleted == null)) {
                this.TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOperationCompleted);
            }
            this.InvokeAsync("Test", new object[0], this.TestOperationCompleted, userState);
        }
        
        private void OnTestOperationCompleted(object arg) {
            if ((this.TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCompleted(this, new TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login(string UserName, string Password) {
            object[] results = this.Invoke("Login", new object[] {
                        UserName,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string UserName, string Password) {
            this.LoginAsync(UserName, Password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string UserName, string Password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        UserName,
                        Password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginForOne", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoginForOne(string UserName, string Password) {
            object[] results = this.Invoke("LoginForOne", new object[] {
                        UserName,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginForOneAsync(string UserName, string Password) {
            this.LoginForOneAsync(UserName, Password, null);
        }
        
        /// <remarks/>
        public void LoginForOneAsync(string UserName, string Password, object userState) {
            if ((this.LoginForOneOperationCompleted == null)) {
                this.LoginForOneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginForOneOperationCompleted);
            }
            this.InvokeAsync("LoginForOne", new object[] {
                        UserName,
                        Password}, this.LoginForOneOperationCompleted, userState);
        }
        
        private void OnLoginForOneOperationCompleted(object arg) {
            if ((this.LoginForOneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginForOneCompleted(this, new LoginForOneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginByCardNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoginByCardNo(string CardNo, string Password) {
            object[] results = this.Invoke("LoginByCardNo", new object[] {
                        CardNo,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginByCardNoAsync(string CardNo, string Password) {
            this.LoginByCardNoAsync(CardNo, Password, null);
        }
        
        /// <remarks/>
        public void LoginByCardNoAsync(string CardNo, string Password, object userState) {
            if ((this.LoginByCardNoOperationCompleted == null)) {
                this.LoginByCardNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginByCardNoOperationCompleted);
            }
            this.InvokeAsync("LoginByCardNo", new object[] {
                        CardNo,
                        Password}, this.LoginByCardNoOperationCompleted, userState);
        }
        
        private void OnLoginByCardNoOperationCompleted(object arg) {
            if ((this.LoginByCardNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginByCardNoCompleted(this, new LoginByCardNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginEx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoginEx(string username, string password, string passport, string usertype) {
            object[] results = this.Invoke("LoginEx", new object[] {
                        username,
                        password,
                        passport,
                        usertype});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginExAsync(string username, string password, string passport, string usertype) {
            this.LoginExAsync(username, password, passport, usertype, null);
        }
        
        /// <remarks/>
        public void LoginExAsync(string username, string password, string passport, string usertype, object userState) {
            if ((this.LoginExOperationCompleted == null)) {
                this.LoginExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginExOperationCompleted);
            }
            this.InvokeAsync("LoginEx", new object[] {
                        username,
                        password,
                        passport,
                        usertype}, this.LoginExOperationCompleted, userState);
        }
        
        private void OnLoginExOperationCompleted(object arg) {
            if ((this.LoginExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginExCompleted(this, new LoginExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLoginResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Operator GetLoginResult(string passportID) {
            object[] results = this.Invoke("GetLoginResult", new object[] {
                        passportID});
            return ((Operator)(results[0]));
        }
        
        /// <remarks/>
        public void GetLoginResultAsync(string passportID) {
            this.GetLoginResultAsync(passportID, null);
        }
        
        /// <remarks/>
        public void GetLoginResultAsync(string passportID, object userState) {
            if ((this.GetLoginResultOperationCompleted == null)) {
                this.GetLoginResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoginResultOperationCompleted);
            }
            this.InvokeAsync("GetLoginResult", new object[] {
                        passportID}, this.GetLoginResultOperationCompleted, userState);
        }
        
        private void OnGetLoginResultOperationCompleted(object arg) {
            if ((this.GetLoginResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoginResultCompleted(this, new GetLoginResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogOffX", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LogOffX(string passportID) {
            this.Invoke("LogOffX", new object[] {
                        passportID});
        }
        
        /// <remarks/>
        public void LogOffXAsync(string passportID) {
            this.LogOffXAsync(passportID, null);
        }
        
        /// <remarks/>
        public void LogOffXAsync(string passportID, object userState) {
            if ((this.LogOffXOperationCompleted == null)) {
                this.LogOffXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogOffXOperationCompleted);
            }
            this.InvokeAsync("LogOffX", new object[] {
                        passportID}, this.LogOffXOperationCompleted, userState);
        }
        
        private void OnLogOffXOperationCompleted(object arg) {
            if ((this.LogOffXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogOffXCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangePwd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChangePwd(string UserName, string Password, string NewPassword) {
            object[] results = this.Invoke("ChangePwd", new object[] {
                        UserName,
                        Password,
                        NewPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChangePwdAsync(string UserName, string Password, string NewPassword) {
            this.ChangePwdAsync(UserName, Password, NewPassword, null);
        }
        
        /// <remarks/>
        public void ChangePwdAsync(string UserName, string Password, string NewPassword, object userState) {
            if ((this.ChangePwdOperationCompleted == null)) {
                this.ChangePwdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePwdOperationCompleted);
            }
            this.InvokeAsync("ChangePwd", new object[] {
                        UserName,
                        Password,
                        NewPassword}, this.ChangePwdOperationCompleted, userState);
        }
        
        private void OnChangePwdOperationCompleted(object arg) {
            if ((this.ChangePwdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangePwdCompleted(this, new ChangePwdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XmlSubmit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string XmlSubmit(string identity, string request, string filter) {
            object[] results = this.Invoke("XmlSubmit", new object[] {
                        identity,
                        request,
                        filter});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void XmlSubmitAsync(string identity, string request, string filter) {
            this.XmlSubmitAsync(identity, request, filter, null);
        }
        
        /// <remarks/>
        public void XmlSubmitAsync(string identity, string request, string filter, object userState) {
            if ((this.XmlSubmitOperationCompleted == null)) {
                this.XmlSubmitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXmlSubmitOperationCompleted);
            }
            this.InvokeAsync("XmlSubmit", new object[] {
                        identity,
                        request,
                        filter}, this.XmlSubmitOperationCompleted, userState);
        }
        
        private void OnXmlSubmitOperationCompleted(object arg) {
            if ((this.XmlSubmitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XmlSubmitCompleted(this, new XmlSubmitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XmlSubmitDS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string XmlSubmitDS(string identity, string request, string filter, ref System.Data.DataSet ds) {
            object[] results = this.Invoke("XmlSubmitDS", new object[] {
                        identity,
                        request,
                        filter,
                        ds});
            ds = ((System.Data.DataSet)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void XmlSubmitDSAsync(string identity, string request, string filter, System.Data.DataSet ds) {
            this.XmlSubmitDSAsync(identity, request, filter, ds, null);
        }
        
        /// <remarks/>
        public void XmlSubmitDSAsync(string identity, string request, string filter, System.Data.DataSet ds, object userState) {
            if ((this.XmlSubmitDSOperationCompleted == null)) {
                this.XmlSubmitDSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXmlSubmitDSOperationCompleted);
            }
            this.InvokeAsync("XmlSubmitDS", new object[] {
                        identity,
                        request,
                        filter,
                        ds}, this.XmlSubmitDSOperationCompleted, userState);
        }
        
        private void OnXmlSubmitDSOperationCompleted(object arg) {
            if ((this.XmlSubmitDSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XmlSubmitDSCompleted(this, new XmlSubmitDSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateNewOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateNewOrder(string identity, OrderFlightItem[] flights, OrderPassengerItem[] passengers, OrderPriceItem[] prices) {
            object[] results = this.Invoke("CreateNewOrder", new object[] {
                        identity,
                        flights,
                        passengers,
                        prices});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateNewOrderAsync(string identity, OrderFlightItem[] flights, OrderPassengerItem[] passengers, OrderPriceItem[] prices) {
            this.CreateNewOrderAsync(identity, flights, passengers, prices, null);
        }
        
        /// <remarks/>
        public void CreateNewOrderAsync(string identity, OrderFlightItem[] flights, OrderPassengerItem[] passengers, OrderPriceItem[] prices, object userState) {
            if ((this.CreateNewOrderOperationCompleted == null)) {
                this.CreateNewOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateNewOrderOperationCompleted);
            }
            this.InvokeAsync("CreateNewOrder", new object[] {
                        identity,
                        flights,
                        passengers,
                        prices}, this.CreateNewOrderOperationCompleted, userState);
        }
        
        private void OnCreateNewOrderOperationCompleted(object arg) {
            if ((this.CreateNewOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateNewOrderCompleted(this, new CreateNewOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomerPolicy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCustomerPolicy(string identity, string request, string filter) {
            object[] results = this.Invoke("GetCustomerPolicy", new object[] {
                        identity,
                        request,
                        filter});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerPolicyAsync(string identity, string request, string filter) {
            this.GetCustomerPolicyAsync(identity, request, filter, null);
        }
        
        /// <remarks/>
        public void GetCustomerPolicyAsync(string identity, string request, string filter, object userState) {
            if ((this.GetCustomerPolicyOperationCompleted == null)) {
                this.GetCustomerPolicyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerPolicyOperationCompleted);
            }
            this.InvokeAsync("GetCustomerPolicy", new object[] {
                        identity,
                        request,
                        filter}, this.GetCustomerPolicyOperationCompleted, userState);
        }
        
        private void OnGetCustomerPolicyOperationCompleted(object arg) {
            if ((this.GetCustomerPolicyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerPolicyCompleted(this, new GetCustomerPolicyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Operator {
        
        private int uIDField;
        
        private string loginIDField;
        
        private string loginNameField;
        
        private string clientIPField;
        
        private SystemUserTypes userTypeField;
        
        private OperatorLoginSource loginSourceField;
        
        private int userLevelField;
        
        private int userIDField;
        
        private string userCodeField;
        
        private string userNameField;
        
        private int departmentIDField;
        
        private string departmentNoField;
        
        private int officeIDField;
        
        private string officeNameField;
        
        private int psrIDField;
        
        private int cusUserIDField;
        
        private string cusUserCodeField;
        
        private string cusUserNameField;
        
        private int customerIDField;
        
        private string customerNoField;
        
        private string customerNameField;
        
        private int policyDepIDField;
        
        private string userPasswordField;
        
        private string callCenterWorkIDField;
        
        private string noValidDtField;
        
        private OperatorJobOwned jobOwndedField;
        
        private string locationField;
        
        private string roleIdField;
        
        private string deptPathField;
        
        private string iMGroupField;
        
        private string iMSubGroupField;
        
        private string etermUserField;
        
        private string etermPwdField;
        
        private string sAASCusNoField;
        
        private int curDistributorRuleField;
        
        private int customerReturnGainRuleField;
        
        private int customerReturnGain2TypeField;
        
        private int curSupplierRuleField;
        
        private bool isSAgentField;
        
        private string ticketCityField;
        
        private string isHideGainField;
        
        /// <remarks/>
        public int UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
        
        /// <remarks/>
        public string LoginID {
            get {
                return this.loginIDField;
            }
            set {
                this.loginIDField = value;
            }
        }
        
        /// <remarks/>
        public string LoginName {
            get {
                return this.loginNameField;
            }
            set {
                this.loginNameField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIP {
            get {
                return this.clientIPField;
            }
            set {
                this.clientIPField = value;
            }
        }
        
        /// <remarks/>
        public SystemUserTypes UserType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
            }
        }
        
        /// <remarks/>
        public OperatorLoginSource LoginSource {
            get {
                return this.loginSourceField;
            }
            set {
                this.loginSourceField = value;
            }
        }
        
        /// <remarks/>
        public int UserLevel {
            get {
                return this.userLevelField;
            }
            set {
                this.userLevelField = value;
            }
        }
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserCode {
            get {
                return this.userCodeField;
            }
            set {
                this.userCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public int DepartmentID {
            get {
                return this.departmentIDField;
            }
            set {
                this.departmentIDField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentNo {
            get {
                return this.departmentNoField;
            }
            set {
                this.departmentNoField = value;
            }
        }
        
        /// <remarks/>
        public int OfficeID {
            get {
                return this.officeIDField;
            }
            set {
                this.officeIDField = value;
            }
        }
        
        /// <remarks/>
        public string OfficeName {
            get {
                return this.officeNameField;
            }
            set {
                this.officeNameField = value;
            }
        }
        
        /// <remarks/>
        public int PsrID {
            get {
                return this.psrIDField;
            }
            set {
                this.psrIDField = value;
            }
        }
        
        /// <remarks/>
        public int CusUserID {
            get {
                return this.cusUserIDField;
            }
            set {
                this.cusUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string CusUserCode {
            get {
                return this.cusUserCodeField;
            }
            set {
                this.cusUserCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CusUserName {
            get {
                return this.cusUserNameField;
            }
            set {
                this.cusUserNameField = value;
            }
        }
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerNo {
            get {
                return this.customerNoField;
            }
            set {
                this.customerNoField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public int PolicyDepID {
            get {
                return this.policyDepIDField;
            }
            set {
                this.policyDepIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserPassword {
            get {
                return this.userPasswordField;
            }
            set {
                this.userPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string CallCenterWorkID {
            get {
                return this.callCenterWorkIDField;
            }
            set {
                this.callCenterWorkIDField = value;
            }
        }
        
        /// <remarks/>
        public string NoValidDt {
            get {
                return this.noValidDtField;
            }
            set {
                this.noValidDtField = value;
            }
        }
        
        /// <remarks/>
        public OperatorJobOwned JobOwnded {
            get {
                return this.jobOwndedField;
            }
            set {
                this.jobOwndedField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
            }
        }
        
        /// <remarks/>
        public string DeptPath {
            get {
                return this.deptPathField;
            }
            set {
                this.deptPathField = value;
            }
        }
        
        /// <remarks/>
        public string IMGroup {
            get {
                return this.iMGroupField;
            }
            set {
                this.iMGroupField = value;
            }
        }
        
        /// <remarks/>
        public string IMSubGroup {
            get {
                return this.iMSubGroupField;
            }
            set {
                this.iMSubGroupField = value;
            }
        }
        
        /// <remarks/>
        public string EtermUser {
            get {
                return this.etermUserField;
            }
            set {
                this.etermUserField = value;
            }
        }
        
        /// <remarks/>
        public string EtermPwd {
            get {
                return this.etermPwdField;
            }
            set {
                this.etermPwdField = value;
            }
        }
        
        /// <remarks/>
        public string SAASCusNo {
            get {
                return this.sAASCusNoField;
            }
            set {
                this.sAASCusNoField = value;
            }
        }
        
        /// <remarks/>
        public int CurDistributorRule {
            get {
                return this.curDistributorRuleField;
            }
            set {
                this.curDistributorRuleField = value;
            }
        }
        
        /// <remarks/>
        public int CustomerReturnGainRule {
            get {
                return this.customerReturnGainRuleField;
            }
            set {
                this.customerReturnGainRuleField = value;
            }
        }
        
        /// <remarks/>
        public int CustomerReturnGain2Type {
            get {
                return this.customerReturnGain2TypeField;
            }
            set {
                this.customerReturnGain2TypeField = value;
            }
        }
        
        /// <remarks/>
        public int CurSupplierRule {
            get {
                return this.curSupplierRuleField;
            }
            set {
                this.curSupplierRuleField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSAgent {
            get {
                return this.isSAgentField;
            }
            set {
                this.isSAgentField = value;
            }
        }
        
        /// <remarks/>
        public string TicketCity {
            get {
                return this.ticketCityField;
            }
            set {
                this.ticketCityField = value;
            }
        }
        
        /// <remarks/>
        public string IsHideGain {
            get {
                return this.isHideGainField;
            }
            set {
                this.isHideGainField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SystemUserTypes {
        
        /// <remarks/>
        Platform,
        
        /// <remarks/>
        Distributor,
        
        /// <remarks/>
        Agent,
        
        /// <remarks/>
        Supplier,
        
        /// <remarks/>
        Member,
        
        /// <remarks/>
        SuperPlatform,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum OperatorLoginSource {
        
        /// <remarks/>
        Platform,
        
        /// <remarks/>
        WebClient,
        
        /// <remarks/>
        Client,
        
        /// <remarks/>
        YSTA,
        
        /// <remarks/>
        ATS,
        
        /// <remarks/>
        S,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OperatorJobOwned {
        
        private bool phoneOperatorField;
        
        private bool tktOperatorField;
        
        private bool depManagerField;
        
        private bool cusManagerField;
        
        private bool delivererField;
        
        private bool cashierField;
        
        private bool qMailOperatorField;
        
        /// <remarks/>
        public bool PhoneOperator {
            get {
                return this.phoneOperatorField;
            }
            set {
                this.phoneOperatorField = value;
            }
        }
        
        /// <remarks/>
        public bool TktOperator {
            get {
                return this.tktOperatorField;
            }
            set {
                this.tktOperatorField = value;
            }
        }
        
        /// <remarks/>
        public bool DepManager {
            get {
                return this.depManagerField;
            }
            set {
                this.depManagerField = value;
            }
        }
        
        /// <remarks/>
        public bool CusManager {
            get {
                return this.cusManagerField;
            }
            set {
                this.cusManagerField = value;
            }
        }
        
        /// <remarks/>
        public bool Deliverer {
            get {
                return this.delivererField;
            }
            set {
                this.delivererField = value;
            }
        }
        
        /// <remarks/>
        public bool Cashier {
            get {
                return this.cashierField;
            }
            set {
                this.cashierField = value;
            }
        }
        
        /// <remarks/>
        public bool QMailOperator {
            get {
                return this.qMailOperatorField;
            }
            set {
                this.qMailOperatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderPriceItem {
        
        private string priceKeyField;
        
        private decimal cusFareField;
        
        private decimal fareField;
        
        private decimal fare2Field;
        
        private decimal airportTaxField;
        
        private decimal fuelTaxField;
        
        private decimal taxAmountField;
        
        private decimal customerGainField;
        
        private decimal customerGain2Field;
        
        private decimal customerMoneyField;
        
        private decimal agentGainField;
        
        private decimal agentGain2Field;
        
        private decimal agentMoneyField;
        
        private decimal tktNetPriceField;
        
        private decimal paymentFeeField;
        
        private decimal businessFeeField;
        
        private decimal bookingFeeField;
        
        private decimal refundFeeField;
        
        private decimal changeFeeField;
        
        private decimal affixFeeField;
        
        private int tktCountField;
        
        private decimal balanceMoneyField;
        
        private decimal customerFee1Field;
        
        private decimal customerFee2Field;
        
        private decimal customerReturnGainField;
        
        private decimal vipCustomerFeeField;
        
        private decimal agentFee1Field;
        
        private decimal agentFee2Field;
        
        private decimal overInvoiceField;
        
        private decimal curSupplierMoneyField;
        
        private decimal supplierMoneyField;
        
        private ProductTypes productTypeField;
        
        private string priceIDField;
        
        private string priceRemarkField;
        
        private int providerCodeField;
        
        private string crsPnrField;
        
        private string psrTypeField;
        
        private int psrCountField;
        
        private string airlineField;
        
        private string tktDetailField;
        
        private string iSPriceSQField;
        
        private decimal sAgentFee1Field;
        
        private decimal sAgentGainField;
        
        private string ticketOfficeField;
        
        private decimal carrierChangeFeeField;
        
        private bool carrierSettleStField;
        
        private decimal carrierSettlerAdjustField;
        
        private string carrierSettleDtField;
        
        /// <remarks/>
        public string PriceKey {
            get {
                return this.priceKeyField;
            }
            set {
                this.priceKeyField = value;
            }
        }
        
        /// <remarks/>
        public decimal CusFare {
            get {
                return this.cusFareField;
            }
            set {
                this.cusFareField = value;
            }
        }
        
        /// <remarks/>
        public decimal Fare {
            get {
                return this.fareField;
            }
            set {
                this.fareField = value;
            }
        }
        
        /// <remarks/>
        public decimal Fare2 {
            get {
                return this.fare2Field;
            }
            set {
                this.fare2Field = value;
            }
        }
        
        /// <remarks/>
        public decimal AirportTax {
            get {
                return this.airportTaxField;
            }
            set {
                this.airportTaxField = value;
            }
        }
        
        /// <remarks/>
        public decimal FuelTax {
            get {
                return this.fuelTaxField;
            }
            set {
                this.fuelTaxField = value;
            }
        }
        
        /// <remarks/>
        public decimal TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        public decimal CustomerGain {
            get {
                return this.customerGainField;
            }
            set {
                this.customerGainField = value;
            }
        }
        
        /// <remarks/>
        public decimal CustomerGain2 {
            get {
                return this.customerGain2Field;
            }
            set {
                this.customerGain2Field = value;
            }
        }
        
        /// <remarks/>
        public decimal CustomerMoney {
            get {
                return this.customerMoneyField;
            }
            set {
                this.customerMoneyField = value;
            }
        }
        
        /// <remarks/>
        public decimal AgentGain {
            get {
                return this.agentGainField;
            }
            set {
                this.agentGainField = value;
            }
        }
        
        /// <remarks/>
        public decimal AgentGain2 {
            get {
                return this.agentGain2Field;
            }
            set {
                this.agentGain2Field = value;
            }
        }
        
        /// <remarks/>
        public decimal AgentMoney {
            get {
                return this.agentMoneyField;
            }
            set {
                this.agentMoneyField = value;
            }
        }
        
        /// <remarks/>
        public decimal TktNetPrice {
            get {
                return this.tktNetPriceField;
            }
            set {
                this.tktNetPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal PaymentFee {
            get {
                return this.paymentFeeField;
            }
            set {
                this.paymentFeeField = value;
            }
        }
        
        /// <remarks/>
        public decimal BusinessFee {
            get {
                return this.businessFeeField;
            }
            set {
                this.businessFeeField = value;
            }
        }
        
        /// <remarks/>
        public decimal BookingFee {
            get {
                return this.bookingFeeField;
            }
            set {
                this.bookingFeeField = value;
            }
        }
        
        /// <remarks/>
        public decimal RefundFee {
            get {
                return this.refundFeeField;
            }
            set {
                this.refundFeeField = value;
            }
        }
        
        /// <remarks/>
        public decimal ChangeFee {
            get {
                return this.changeFeeField;
            }
            set {
                this.changeFeeField = value;
            }
        }
        
        /// <remarks/>
        public decimal AffixFee {
            get {
                return this.affixFeeField;
            }
            set {
                this.affixFeeField = value;
            }
        }
        
        /// <remarks/>
        public int TktCount {
            get {
                return this.tktCountField;
            }
            set {
                this.tktCountField = value;
            }
        }
        
        /// <remarks/>
        public decimal BalanceMoney {
            get {
                return this.balanceMoneyField;
            }
            set {
                this.balanceMoneyField = value;
            }
        }
        
        /// <remarks/>
        public decimal CustomerFee1 {
            get {
                return this.customerFee1Field;
            }
            set {
                this.customerFee1Field = value;
            }
        }
        
        /// <remarks/>
        public decimal CustomerFee2 {
            get {
                return this.customerFee2Field;
            }
            set {
                this.customerFee2Field = value;
            }
        }
        
        /// <remarks/>
        public decimal CustomerReturnGain {
            get {
                return this.customerReturnGainField;
            }
            set {
                this.customerReturnGainField = value;
            }
        }
        
        /// <remarks/>
        public decimal VipCustomerFee {
            get {
                return this.vipCustomerFeeField;
            }
            set {
                this.vipCustomerFeeField = value;
            }
        }
        
        /// <remarks/>
        public decimal AgentFee1 {
            get {
                return this.agentFee1Field;
            }
            set {
                this.agentFee1Field = value;
            }
        }
        
        /// <remarks/>
        public decimal AgentFee2 {
            get {
                return this.agentFee2Field;
            }
            set {
                this.agentFee2Field = value;
            }
        }
        
        /// <remarks/>
        public decimal OverInvoice {
            get {
                return this.overInvoiceField;
            }
            set {
                this.overInvoiceField = value;
            }
        }
        
        /// <remarks/>
        public decimal CurSupplierMoney {
            get {
                return this.curSupplierMoneyField;
            }
            set {
                this.curSupplierMoneyField = value;
            }
        }
        
        /// <remarks/>
        public decimal SupplierMoney {
            get {
                return this.supplierMoneyField;
            }
            set {
                this.supplierMoneyField = value;
            }
        }
        
        /// <remarks/>
        public ProductTypes ProductType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PriceID {
            get {
                return this.priceIDField;
            }
            set {
                this.priceIDField = value;
            }
        }
        
        /// <remarks/>
        public string PriceRemark {
            get {
                return this.priceRemarkField;
            }
            set {
                this.priceRemarkField = value;
            }
        }
        
        /// <remarks/>
        public int ProviderCode {
            get {
                return this.providerCodeField;
            }
            set {
                this.providerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CrsPnr {
            get {
                return this.crsPnrField;
            }
            set {
                this.crsPnrField = value;
            }
        }
        
        /// <remarks/>
        public string PsrType {
            get {
                return this.psrTypeField;
            }
            set {
                this.psrTypeField = value;
            }
        }
        
        /// <remarks/>
        public int PsrCount {
            get {
                return this.psrCountField;
            }
            set {
                this.psrCountField = value;
            }
        }
        
        /// <remarks/>
        public string Airline {
            get {
                return this.airlineField;
            }
            set {
                this.airlineField = value;
            }
        }
        
        /// <remarks/>
        public string TktDetail {
            get {
                return this.tktDetailField;
            }
            set {
                this.tktDetailField = value;
            }
        }
        
        /// <remarks/>
        public string ISPriceSQ {
            get {
                return this.iSPriceSQField;
            }
            set {
                this.iSPriceSQField = value;
            }
        }
        
        /// <remarks/>
        public decimal SAgentFee1 {
            get {
                return this.sAgentFee1Field;
            }
            set {
                this.sAgentFee1Field = value;
            }
        }
        
        /// <remarks/>
        public decimal SAgentGain {
            get {
                return this.sAgentGainField;
            }
            set {
                this.sAgentGainField = value;
            }
        }
        
        /// <remarks/>
        public string TicketOffice {
            get {
                return this.ticketOfficeField;
            }
            set {
                this.ticketOfficeField = value;
            }
        }
        
        /// <remarks/>
        public decimal CarrierChangeFee {
            get {
                return this.carrierChangeFeeField;
            }
            set {
                this.carrierChangeFeeField = value;
            }
        }
        
        /// <remarks/>
        public bool CarrierSettleSt {
            get {
                return this.carrierSettleStField;
            }
            set {
                this.carrierSettleStField = value;
            }
        }
        
        /// <remarks/>
        public decimal CarrierSettlerAdjust {
            get {
                return this.carrierSettlerAdjustField;
            }
            set {
                this.carrierSettlerAdjustField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierSettleDt {
            get {
                return this.carrierSettleDtField;
            }
            set {
                this.carrierSettleDtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ProductTypes {
        
        /// <remarks/>
        JP,
        
        /// <remarks/>
        BX,
        
        /// <remarks/>
        HC,
        
        /// <remarks/>
        JD,
        
        /// <remarks/>
        GN,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderPassengerItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PassengerSegment {
        
        private PassengerLevel psrlevelField;
        
        private int idField;
        
        private int elementNoField;
        
        private int psgIDField;
        
        private int customerPsgIDField;
        
        private string nameField;
        
        private CRSPassengerTypes psgTypeField;
        
        private string cardTypeField;
        
        private string cardNoField;
        
        private string birthDayField;
        
        private int carrierPsgIDField;
        
        private string countryField;
        
        private string ticketNoField;
        
        private string mobilePhoneField;
        
        private string carrierCardField;
        
        private int insueSumField;
        
        private decimal insueFeeField;
        
        private decimal netInsueFeeField;
        
        private int insueProductIDField;
        
        private decimal serviceFeeField;
        
        private string genderField;
        
        private string fNNoField;
        
        private string cKProductField;
        
        private string cKCardNoField;
        
        private System.Nullable<System.DateTime> cardValidDateField;
        
        private string visaCountryField;
        
        private PassengerLevel psrLevelField;
        
        private string warningField;
        
        private string insuranceFlightNoField;
        
        /// <remarks/>
        public PassengerLevel psrlevel {
            get {
                return this.psrlevelField;
            }
            set {
                this.psrlevelField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ElementNo {
            get {
                return this.elementNoField;
            }
            set {
                this.elementNoField = value;
            }
        }
        
        /// <remarks/>
        public int PsgID {
            get {
                return this.psgIDField;
            }
            set {
                this.psgIDField = value;
            }
        }
        
        /// <remarks/>
        public int CustomerPsgID {
            get {
                return this.customerPsgIDField;
            }
            set {
                this.customerPsgIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public CRSPassengerTypes PsgType {
            get {
                return this.psgTypeField;
            }
            set {
                this.psgTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CardNo {
            get {
                return this.cardNoField;
            }
            set {
                this.cardNoField = value;
            }
        }
        
        /// <remarks/>
        public string BirthDay {
            get {
                return this.birthDayField;
            }
            set {
                this.birthDayField = value;
            }
        }
        
        /// <remarks/>
        public int CarrierPsgID {
            get {
                return this.carrierPsgIDField;
            }
            set {
                this.carrierPsgIDField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string TicketNo {
            get {
                return this.ticketNoField;
            }
            set {
                this.ticketNoField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierCard {
            get {
                return this.carrierCardField;
            }
            set {
                this.carrierCardField = value;
            }
        }
        
        /// <remarks/>
        public int InsueSum {
            get {
                return this.insueSumField;
            }
            set {
                this.insueSumField = value;
            }
        }
        
        /// <remarks/>
        public decimal InsueFee {
            get {
                return this.insueFeeField;
            }
            set {
                this.insueFeeField = value;
            }
        }
        
        /// <remarks/>
        public decimal NetInsueFee {
            get {
                return this.netInsueFeeField;
            }
            set {
                this.netInsueFeeField = value;
            }
        }
        
        /// <remarks/>
        public int InsueProductID {
            get {
                return this.insueProductIDField;
            }
            set {
                this.insueProductIDField = value;
            }
        }
        
        /// <remarks/>
        public decimal ServiceFee {
            get {
                return this.serviceFeeField;
            }
            set {
                this.serviceFeeField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string FNNo {
            get {
                return this.fNNoField;
            }
            set {
                this.fNNoField = value;
            }
        }
        
        /// <remarks/>
        public string CKProduct {
            get {
                return this.cKProductField;
            }
            set {
                this.cKProductField = value;
            }
        }
        
        /// <remarks/>
        public string CKCardNo {
            get {
                return this.cKCardNoField;
            }
            set {
                this.cKCardNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CardValidDate {
            get {
                return this.cardValidDateField;
            }
            set {
                this.cardValidDateField = value;
            }
        }
        
        /// <remarks/>
        public string VisaCountry {
            get {
                return this.visaCountryField;
            }
            set {
                this.visaCountryField = value;
            }
        }
        
        /// <remarks/>
        public PassengerLevel PsrLevel {
            get {
                return this.psrLevelField;
            }
            set {
                this.psrLevelField = value;
            }
        }
        
        /// <remarks/>
        public string Warning {
            get {
                return this.warningField;
            }
            set {
                this.warningField = value;
            }
        }
        
        /// <remarks/>
        public string InsuranceFlightNo {
            get {
                return this.insuranceFlightNoField;
            }
            set {
                this.insuranceFlightNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum PassengerLevel {
        
        /// <remarks/>
        Generral,
        
        /// <remarks/>
        VIP,
        
        /// <remarks/>
        SVIP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum CRSPassengerTypes {
        
        /// <remarks/>
        ADT,
        
        /// <remarks/>
        INF,
        
        /// <remarks/>
        CHD,
        
        /// <remarks/>
        UM,
        
        /// <remarks/>
        MIP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderPassengerItem : PassengerSegment {
        
        private string keyField;
        
        private string countryNameField;
        
        private string visaCountryNameField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        public string VisaCountryName {
            get {
                return this.visaCountryNameField;
            }
            set {
                this.visaCountryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderFlightItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FlightSegment {
        
        private int elementNoField;
        
        private int idField;
        
        private string carrierField;
        
        private string flightNoField;
        
        private string shareCarrierField;
        
        private string shareFlightField;
        
        private string boardPointField;
        
        private string boardPointATField;
        
        private string offPointField;
        
        private string offPointATField;
        
        private int stopField;
        
        private System.Nullable<System.DateTime> departureDateField;
        
        private string departureTimeField;
        
        private System.Nullable<System.DateTime> arrivalDateField;
        
        private string arrivalTimeField;
        
        private string classCodeField;
        
        private string classCodeExField;
        
        private string airCraftField;
        
        private decimal yPriceField;
        
        private decimal minPriceField;
        
        private decimal priceField;
        
        private decimal classRebateField;
        
        private decimal fuelSurFaxField;
        
        private decimal airportTaxField;
        
        private string seatField;
        
        private string groupField;
        
        private string notValidBefField;
        
        private string notValidAftField;
        
        private string allowField;
        
        private string actionCodeField;
        
        private string bookingOfficeField;
        
        private string typeField;
        
        private string fltTypeField;
        
        private string statusField;
        
        private string farebasisField;
        
        private string ticketOfficeField;
        
        private string priceIDField;
        
        private string crsPnrField;
        
        private string pNRField;
        
        private string carrierCustomerNoField;
        
        private int overstepPriceReasonField;
        
        private string priceTypeField;
        
        private string iCSPNRField;
        
        private string originalPNRField;
        
        private string originalFlightField;
        
        private string isReschduleField;
        
        /// <remarks/>
        public int ElementNo {
            get {
                return this.elementNoField;
            }
            set {
                this.elementNoField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Carrier {
            get {
                return this.carrierField;
            }
            set {
                this.carrierField = value;
            }
        }
        
        /// <remarks/>
        public string FlightNo {
            get {
                return this.flightNoField;
            }
            set {
                this.flightNoField = value;
            }
        }
        
        /// <remarks/>
        public string ShareCarrier {
            get {
                return this.shareCarrierField;
            }
            set {
                this.shareCarrierField = value;
            }
        }
        
        /// <remarks/>
        public string ShareFlight {
            get {
                return this.shareFlightField;
            }
            set {
                this.shareFlightField = value;
            }
        }
        
        /// <remarks/>
        public string BoardPoint {
            get {
                return this.boardPointField;
            }
            set {
                this.boardPointField = value;
            }
        }
        
        /// <remarks/>
        public string BoardPointAT {
            get {
                return this.boardPointATField;
            }
            set {
                this.boardPointATField = value;
            }
        }
        
        /// <remarks/>
        public string OffPoint {
            get {
                return this.offPointField;
            }
            set {
                this.offPointField = value;
            }
        }
        
        /// <remarks/>
        public string OffPointAT {
            get {
                return this.offPointATField;
            }
            set {
                this.offPointATField = value;
            }
        }
        
        /// <remarks/>
        public int Stop {
            get {
                return this.stopField;
            }
            set {
                this.stopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DepartureDate {
            get {
                return this.departureDateField;
            }
            set {
                this.departureDateField = value;
            }
        }
        
        /// <remarks/>
        public string DepartureTime {
            get {
                return this.departureTimeField;
            }
            set {
                this.departureTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ArrivalDate {
            get {
                return this.arrivalDateField;
            }
            set {
                this.arrivalDateField = value;
            }
        }
        
        /// <remarks/>
        public string ArrivalTime {
            get {
                return this.arrivalTimeField;
            }
            set {
                this.arrivalTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClassCodeEx {
            get {
                return this.classCodeExField;
            }
            set {
                this.classCodeExField = value;
            }
        }
        
        /// <remarks/>
        public string AirCraft {
            get {
                return this.airCraftField;
            }
            set {
                this.airCraftField = value;
            }
        }
        
        /// <remarks/>
        public decimal YPrice {
            get {
                return this.yPriceField;
            }
            set {
                this.yPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal MinPrice {
            get {
                return this.minPriceField;
            }
            set {
                this.minPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public decimal ClassRebate {
            get {
                return this.classRebateField;
            }
            set {
                this.classRebateField = value;
            }
        }
        
        /// <remarks/>
        public decimal FuelSurFax {
            get {
                return this.fuelSurFaxField;
            }
            set {
                this.fuelSurFaxField = value;
            }
        }
        
        /// <remarks/>
        public decimal AirportTax {
            get {
                return this.airportTaxField;
            }
            set {
                this.airportTaxField = value;
            }
        }
        
        /// <remarks/>
        public string Seat {
            get {
                return this.seatField;
            }
            set {
                this.seatField = value;
            }
        }
        
        /// <remarks/>
        public string Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        public string NotValidBef {
            get {
                return this.notValidBefField;
            }
            set {
                this.notValidBefField = value;
            }
        }
        
        /// <remarks/>
        public string NotValidAft {
            get {
                return this.notValidAftField;
            }
            set {
                this.notValidAftField = value;
            }
        }
        
        /// <remarks/>
        public string Allow {
            get {
                return this.allowField;
            }
            set {
                this.allowField = value;
            }
        }
        
        /// <remarks/>
        public string ActionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BookingOffice {
            get {
                return this.bookingOfficeField;
            }
            set {
                this.bookingOfficeField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string FltType {
            get {
                return this.fltTypeField;
            }
            set {
                this.fltTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Farebasis {
            get {
                return this.farebasisField;
            }
            set {
                this.farebasisField = value;
            }
        }
        
        /// <remarks/>
        public string TicketOffice {
            get {
                return this.ticketOfficeField;
            }
            set {
                this.ticketOfficeField = value;
            }
        }
        
        /// <remarks/>
        public string PriceID {
            get {
                return this.priceIDField;
            }
            set {
                this.priceIDField = value;
            }
        }
        
        /// <remarks/>
        public string CrsPnr {
            get {
                return this.crsPnrField;
            }
            set {
                this.crsPnrField = value;
            }
        }
        
        /// <remarks/>
        public string PNR {
            get {
                return this.pNRField;
            }
            set {
                this.pNRField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierCustomerNo {
            get {
                return this.carrierCustomerNoField;
            }
            set {
                this.carrierCustomerNoField = value;
            }
        }
        
        /// <remarks/>
        public int OverstepPriceReason {
            get {
                return this.overstepPriceReasonField;
            }
            set {
                this.overstepPriceReasonField = value;
            }
        }
        
        /// <remarks/>
        public string PriceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ICSPNR {
            get {
                return this.iCSPNRField;
            }
            set {
                this.iCSPNRField = value;
            }
        }
        
        /// <remarks/>
        public string OriginalPNR {
            get {
                return this.originalPNRField;
            }
            set {
                this.originalPNRField = value;
            }
        }
        
        /// <remarks/>
        public string OriginalFlight {
            get {
                return this.originalFlightField;
            }
            set {
                this.originalFlightField = value;
            }
        }
        
        /// <remarks/>
        public string IsReschdule {
            get {
                return this.isReschduleField;
            }
            set {
                this.isReschduleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderFlightItem : FlightSegment {
        
        private string orderNoField;
        
        private int noField;
        
        private int providerCodeField;
        
        private B2BPolicyPlatforms tktPlatformIDField;
        
        private string keyField;
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public int No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public int ProviderCode {
            get {
                return this.providerCodeField;
            }
            set {
                this.providerCodeField = value;
            }
        }
        
        /// <remarks/>
        public B2BPolicyPlatforms TktPlatformID {
            get {
                return this.tktPlatformIDField;
            }
            set {
                this.tktPlatformIDField = value;
            }
        }
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum B2BPolicyPlatforms {
        
        /// <remarks/>
        YeeSoho,
        
        /// <remarks/>
        ChinaPNRNetB2B,
        
        /// <remarks/>
        Beijing51Book,
        
        /// <remarks/>
        PiaoMeng,
        
        /// <remarks/>
        ChengDu517Na,
        
        /// <remarks/>
        TravelSky,
        
        /// <remarks/>
        I_SHA0255,
        
        /// <remarks/>
        I_BJS0027,
        
        /// <remarks/>
        I_CTU0120,
        
        /// <remarks/>
        BaiTour,
        
        /// <remarks/>
        I_BJS0042,
        
        /// <remarks/>
        I_BJS0069,
        
        /// <remarks/>
        AliDzNetB2B,
        
        /// <remarks/>
        ChengDu8000Yi,
        
        /// <remarks/>
        JinRi,
        
        /// <remarks/>
        YeeXing,
        
        /// <remarks/>
        YeeGo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void TestCompletedEventHandler(object sender, TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void LoginForOneCompletedEventHandler(object sender, LoginForOneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginForOneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginForOneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void LoginByCardNoCompletedEventHandler(object sender, LoginByCardNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginByCardNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginByCardNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void LoginExCompletedEventHandler(object sender, LoginExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetLoginResultCompletedEventHandler(object sender, GetLoginResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoginResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoginResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Operator Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Operator)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void LogOffXCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ChangePwdCompletedEventHandler(object sender, ChangePwdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangePwdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangePwdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void XmlSubmitCompletedEventHandler(object sender, XmlSubmitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XmlSubmitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XmlSubmitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void XmlSubmitDSCompletedEventHandler(object sender, XmlSubmitDSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XmlSubmitDSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XmlSubmitDSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet ds {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void CreateNewOrderCompletedEventHandler(object sender, CreateNewOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateNewOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateNewOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetCustomerPolicyCompletedEventHandler(object sender, GetCustomerPolicyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerPolicyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerPolicyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591