//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3649
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eyousoft_yhq.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://smc.myvo.cn/SMSWebService/Service.asmx")]
        public string Eyousoft_yhq_Web_cn_myvo_smc_Service {
            get {
                return ((string)(this["Eyousoft_yhq_Web_cn_myvo_smc_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sms.2office.net:8080/WebService/SmsService.asmx")]
        public string Eyousoft_yhq_Web_net_2office_sms_SmsService {
            get {
                return ((string)(this["Eyousoft_yhq_Web_net_2office_sms_SmsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://voicesms.2office.net:8080/WebService/VoiceVerificationService.asmx")]
        public string Eyousoft_yhq_Web_net_2office_voicesms_VoiceVerificationService {
            get {
                return ((string)(this["Eyousoft_yhq_Web_net_2office_voicesms_VoiceVerificationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://124.42.75.134:8086/aois/ysta.asmx")]
        public string Eyousoft_yhq_Web_WebReference_Service {
            get {
                return ((string)(this["Eyousoft_yhq_Web_WebReference_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://124.42.75.134:8087/aois/ysta.asmx")]
        public string Eyousoft_yhq_Web_WebReference1_Service {
            get {
                return ((string)(this["Eyousoft_yhq_Web_WebReference1_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://fxad.8222666.com/aois/ysta.asmx")]
        public string Eyousoft_yhq_Web_com_8222666_fxb2b_Service {
            get {
                return ((string)(this["Eyousoft_yhq_Web_com_8222666_fxb2b_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://fxb2b.8222666.com/aois/ysta.asmx")]
        public string Eyousoft_yhq_Web_com_8222666_fxs_Service {
            get {
                return ((string)(this["Eyousoft_yhq_Web_com_8222666_fxs_Service"]));
            }
        }
    }
}
